spring:
  application:
    name: micro-service-admin
  zipkin:
    base-url: http://localhost:9411

server:
  port: 8084

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/